Экзамен
Imsamaboy/2022-2-VK-EDU-FS-Frontend-S-Felshtyn pull request #11
Opened 2022-12-30 14:34 UTC by Imsamaboy

# Домашнее задание №

Прошу @martinkomitsky или @haseprogram проверить его.

Экзамен:

- [ ] В корневой папке репозитория создать базовое приложение `exam` с помощью [CRA](https://github.com/facebook/create-react-app#quick-overview) по инструкции выше
- [ ] Сверстать 2 страницы и необходимые компоненты. Использовать стили
- [ ] Реализовать перевод с одного языка на другой (хорошо, если можно будет выбрать язык из выпадающего списка)
- [ ] Реализовать перевод с неизвестного языка (автоопределитель из `API`)
- [ ] Сохранять историю переводов в `localStorage`
- [ ] Использовать `Redux`
- [ ] Использовать `React-router` для перехода между страницами
- [ ] Задеплоить решение, используя `GitHub Actions`
- [ ] Теория: Объяснить, почему были использованы те или иные инструменты, участки кода и механизмы при решении задачи. Ответить на теоретические вопросы (пункт выполняется лично с преподавателем)
- [ ] Ревью: получить правки по коду и исправить их (получаются лично у преподавателя и выполняются самостоятельно)

2022-12-30 18:42 UTC, martinkomitsky requested changes
Ждем доделки

2022-12-30 20:56 UTC, Imsamaboy commented
Где-то накосячил со стилями (глаза замылились...), но на функциональность никак не влияет :В

2022-12-31 12:23 UTC, martinkomitsky requested changes
Нет фичи для выбора языка
<img width="296" alt="image" src="https://user-images.githubusercontent.com/14847018/210136619-b02364af-9a58-46d2-8b33-dbda5944309b.png">
это параметр `from` в API (см. задание)

2023-01-02 16:05 UTC, Imsamaboy commented
@martinkomitsky добавил фичу!

2023-01-02 17:47 UTC, martinkomitsky approved these changes
31

2023-01-02 17:48 UTC, merged