ДЗ №5
Imsamaboy/2022-2-VK-EDU-FS-Frontend-S-Felshtyn pull request #6
Opened 2022-11-17 19:16 UTC by Imsamaboy

# Домашнее задание №5

Прошу @martinkomitsky или @haseprogram проверить его.

Что было сделано:
Обёрнуто в React :)

2022-11-19 20:37 UTC, martinkomitsky commented on react-chat/package.json
> +  "homepage": "https://imsamaboy.github.io/react-chat",
Должно быть так: https://imsamaboy.github.io/2022-2-VK-EDU-FS-Frontend-S-Felshtyn/

Ведь иначе не работает. Не проверял?

2022-11-19 20:38 UTC, martinkomitsky commented on react-chat/src/components/CreateChatButton.js
> +            <span className="material-symbols-outlined">add_circle</span>
заменить иконки как сказано в условии ДЗ

2022-11-19 20:40 UTC, martinkomitsky requested changes
Фикс комментов

2022-11-23 17:48 UTC, Imsamaboy commented on react-chat/package.json
> +  "homepage": "https://imsamaboy.github.io/react-chat",
Проверял :В

2022-11-23 17:48 UTC, Imsamaboy commented on react-chat/src/components/CreateChatButton.js
> +            <span className="material-symbols-outlined">add_circle</span>
Комментарий отработан

2022-11-24 09:08 UTC, martinkomitsky approved these changes
10

2022-11-24 09:09 UTC, merged